# vim ft=yaml
# travis-ci.org definition for Fail2Ban build (based on nipy configuration)
#
# We pretend to be erlang because we need can't use the python support in
# travis-ci; it uses virtualenvs, they do not have numpy, scipy, matplotlib,
# and it is impractical to build them
language: erlang
env:
    - PYTHON=python PYSUF=''
    # - PYTHON=python3 PYSUF=3 : python3-numpy not currently available
install:
    - sudo apt-get install $PYTHON-all $PYTHON-pyinotify $PYTHON-gamin
script:
    - set -e; for p in `pyversions -s`; do echo "I: $p"; $p ./fail2ban-testcases; done
