# vim ft=yaml
# travis-ci.org definition for Fail2Ban build
language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get update -qq
install:
  - pip install pyinotify
  - sudo apt-get install -qq python-gamin
  - if [[ $TRAVIS_PYTHON_VERSION == 2.[6-7] ]]; then pip install -q coveralls; fi
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.[6-7] ]]; then coverage run --rcfile=.travis_coveragerc fail2ban-testcases; else python ./fail2ban-testcases; fi
after_script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2.[6-7] ]]; then coveralls; fi
