# vim ft=yaml
# travis-ci.org definition for Fail2Ban build
language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - "pip install pyinotify"
before_script:
    - if [[ $TRAVIS_PYTHON_VERSION == 3* ]]; then ./fail2ban-2to3; fi
script:
    - python ./fail2ban-testcases
